config/routes.rb
Rails.application.routes.draw do
  get 'orders/new'

  get 'malls/index'

  get 'malls/show'

  devise_for :users
  root to: "welcome_page#welcome"
  get '/robots.txt', to: 'welcome_page#robots'


  resources :orders do
    resources :items
  end

  resources :malls
  
  
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :order
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    def new
        ## view calls 'items_list' partial 
        order_id = params[:order_id]
        @order=current_user.orders.find(order_id)
        if @order.nil?
            @order = current_user.orders.create
        end

        @item = @order.items.new

        # this is needed b/c the view calls "items_list" partial
        @items = @order.items
        
        # Side note:
        # In the items_list partial you'll see a check for
        # item.id.nil? This is needed b/c aparently that 
        # @order.items.new is being included in the order.items list.
        # Fuck knows why, and, tbh, who cares.

        # this is needed b/c the view calls "items_list" partial
        @place_order_button = is_place_order_button_needed(@items)
    end

    def is_place_order_button_needed(items)
        # no items at all? 
        # the button is not needed
        if items.length < 1
            return false
        end
        
        # only one item in the order? 
        # check if it is this item.new unreal-real item (it's id will be nil)
        if items.length == 1
            return !items.last.id.nil?
        end

        # more than 1 item? 
        # obviously we need the "place order" button!
        return true
    end

    def edit
        @order = current_user.orders.find(params[:order_id])
        @item = @order.items.find(params[:id])

        # this is needed b/c the view calls "items_list" partial
        @items = @order.items
        @place_order_button = is_place_order_button_needed(@items)
    end

    def create
        order_id = params[:order_id]
        @order = current_user.orders.find(order_id)
        @order.items.create(item_params)
        UserMailer.item_added_email(@order).deliver_now
        # items list is now in the new form 
        # (so that the user can see what's already in the order)
        # so instead of items index path (order_items_path(@order)),
        # redirect to new item path
        redirect_to new_order_item_path(@order)
    end

    def index
        ## view calls 'items_list' partial 
        order_id = params[:order_id]
        @order = current_user.orders.find(order_id)
        @items = @order.items

        # this is needed b/c the view calls "items_list" partial
        @place_order_button = is_place_order_button_needed(@items)
    end

    def update
        order_id = params[:order_id]
        @order = current_user.orders.find(order_id)
        @item = @order.items.find(params[:id])
        @item.update(item_params)
        # items list is now in the new form 
        # (so that the user can see what's already in the order)
        # so instead of items index path (order_items_path(@order)),
        # redirect to new item path
        redirect_to new_order_item_path(@order)
    end

    def destroy
        order_id = params[:order_id]
        @order = current_user.orders.find(order_id)
        @item = @order.items.find(params[:id])
        @item.destroy
        # items list is now in the new form 
        # (so that the user can see what's already in the order)
        # so instead of items index path (order_items_path(@order)),
        # redirect to new item path
        redirect_to new_order_item_path(@order)

    end
    
    private
    def item_params
        params.require(:item).permit(:description, :color, :size)
    end
end

# NOTES:

=begin
    items_list partial is called from index and new
    items_list needs '@items' and '@place_order_button'
    @place_order_button: run is_place_order_button_needed(items)
=end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_item_form.html.erb
<%= form_for ([@order, @item]) do |f| %>     
    
    <div class="form-group">
        <%= f.label :description, "Describe it:" %>
        <%= f.text_area :description, class: "form-control", placeholder: "Black stretch pants, high rise, 3/4 length", :required => true%>
    </div>

    <div class="form-group">
        <%= f.label :color, "What color?" %>
        <%= f.text_field :color, class: "form-control", placeholder: "Black! I told you already!", :required => true%>
    </div>

    <div class="form-group">
        <%= f.label :color, "What size?" %>
        <%= f.text_field :size, class: "form-control", placeholder: "Mmmm, M I think? Maybe L...", :required => true%>
    </div>

    <%= f.submit "Add to cart", class: "btn btn-success my-3" %>

<% end %>

app/views/items/_items_list.html.erb
<% items.each do |item| %>   
    <% unless item.id.nil? %>
        
        <div class="card">
            <div class="card-body">
                <h5 class="card-title"><%=item.description%></h5>
                <p class="card-text">
                    <i>Color:</i> <b><%=item.color%></b><br>
                    <i>Size:</i> <b><%=item.size%></b>
                </p>
                <%= link_to "Edit", edit_order_item_path(item.order, item), class: "btn btn-primary" %>
                <%= link_to "Remove", order_item_path(item.order, item), class: "btn btn-primary", method: :delete %>
            </div>
        </div>
    
    <% end %>
<% end %>

<% if place_order_button %>
    <% @order = items.last.order %>
    <div class="row justify-content-center my-3">
        <div class="column-11">
        <%= link_to "Place order", edit_order_path(@order), class: "btn btn-success btn-block" %>
        </div>
    </div>
<% end %>

app/views/items/edit.html.erb
<div class="container-fluid">
<div class="row justify-content-around">
    
    <div class="column-5 px-3">
        <%= render partial: "item_form" %>
    </div>

    <% if @place_order_button %>
        <div class="column-5 px-3">
            <%= render partial: "items_list", locals: {items: @items, place_order_button: @place_order_button} %>
        </div>
    <% end %>

</div>
</div>

app/views/items/index.html.erb
<div class="container-fluid">
<div class="row justify-content-center">
<div class="column-6 px-3">
    
<%= render partial: "items_list", locals: {items: @items, place_order_button: @place_order_button} %>

</div>    
</div>
</div>

app/views/items/new.html.erb
<div class="container-fluid">
<div class="row justify-content-around">

    <div class="column-5 px-3">
        <%= render partial: "item_form" %>
    </div>

    <% if @place_order_button %>
        <div class="column-5 px-3">
            <%= render partial: "items_list", locals: {items: @items, place_order_button: @place_order_button} %>
        </div>
    <% end %>

</div>
</div>