config/routes.rb
Rails.application.routes.draw do
  get 'orders/new'

  get 'malls/index'

  get 'malls/show'

  devise_for :users
  root to: "welcome_page#welcome"
  get '/robots.txt', to: 'welcome_page#robots'


  resources :orders do
    resources :items
  end

  resources :malls
  
  
end

app/models/mall.rb
class Mall < ApplicationRecord
    acts_as_mappable   
    
    has_many :orders
    has_and_belongs_to_many :stores

    # This is for populating the db with mall locations
    def self.populate
        self.create_location("Riocan Centre Burloak", "3543 Wyecroft Rd, Oakville, ON L6L 0B6")
        self.create_location("Oakville Place", "240 Leighland Ave, Oakville, ON L6H 3H6")
        self.create_location("Mapleview Centre", "900 Maple Ave, Burlington, ON L7S 2J8")
        self.create_location("Burlington Mall", "777 Guelph Line, Burlington, ON L7R 3N2")
    end

    # This is for populating the db with mall locations
    def self.create_location(name, address)
        coords = GEOCODER.geocode(address)
        mall = Mall.find_by(name: name)
        return unless mall.nil?
        Mall.create(name: name, address: address, lat: coords.lat, lng: coords.lng)
    end

    def self.find_by_address(address=nil)
        return nil if address.nil?
        location = GEOCODER.geocode(address)
        # this is ugly but works. Fix leater if you feel like it
        malls = Mall.within(20, :origin => location)
        return nil if malls.count == 0
        return malls.by_distance(:origin=>location)
    end

    def get_distance(address=nil)
        return nil if address.nil?
        location = GEOCODER.geocode(address)
        return self.distance_to(location)
    end

    def get_delivery_price(address=nil)
        return nil if address.nil?
        distance = self.get_distance(address)
        price = (distance * 1.5).round
        price = 5 if price < 5 
        price = 15 if price > 15
        price = price - 0.01
        return price
    end 

    def self.cap
        require 'selenium-webdriver'
        require 'nokogiri'
        require 'capybara'
        Capybara.register_driver :selenium do |app|  
            Capybara::Selenium::Driver.new(app, browser: :chrome)
        end
        Capybara.javascript_driver = :chrome
        Capybara.configure do |config|  
            config.default_max_wait_time = 10 # seconds
            config.default_driver = :selenium
        end
        # Visit
        browser = Capybara.current_session
        driver = browser.driver.browser

        browser.visit("https://avetty.com/")
    end

end

app/controllers/malls_controller.rb
class MallsController < ApplicationController
  def index
      # that is actually supposed to be postal code
      # it was done this way because, you know, what if
      # they enter street or something even though it
      # specifically says "Postal Code" in the search field
      location = params[:location]
      SearchedLocation.create(location:location, user: current_user)
      
      @location = GEOCODER.geocode(location)

      @city = @location.city
      @province = @location.province
      @postal = @location.zip

      order = current_user.orders.last
      order.update(city: @city, province: @province, postal: @postal)

      @malls = Mall.find_by_address(params[:location])
      redirect_to root_path if @malls.nil?
  end

  def show
      # On the malls index page, each mall has select button.
      # This button leads here. But. The user doesn't want to 
      # see the mall, right? They care to start ordering. 
      # So, we'll just record the mall in the order here, and 
      # redirect to the new item page right away 
      mall_id = params[:id]
      order = current_user.orders.last
      order.update(mall_id: mall_id)
      redirect_to new_order_item_path(order.id)
  end


end

app/helpers/malls_helper.rb
module MallsHelper
end

app/views/malls/index.html.erb
<div class="container-fluid">
    
    <div class="row">
        <div class="col-12">
            <h1>We're available <%= @city%>, <%=@province%></h1>
        </div>
        
    </div>
    <hr>

    <% @malls.each do |mall| %>   
        <div class="row">
            <div class="column-4 px-3">
                <p><%=mall.name%></p>
                <p><%=mall.address%></p>
                <%=link_to "Select", mall_path(mall.id), class: "btn btn-success" %>
            </div>
            <div class="column-6 px-3 mall-stores">
                <% mall.stores.each do |store| %>
                    <%= image_tag "#{store.logo}", class: "font-weight-normal m-1 border", alt: "#{store.name} same day delivery" %>
                <% end %>
            </div>
            <div class="column-2 px-3">
                <h5>Delivery: </h5>
                <h3 class="align-middle"><%= number_to_currency(mall.get_delivery_price(@location)) %></h3>    
            </div>
        </div>
        <hr>
    <% end %>
    
</div>

app/views/malls/show.html.erb
<h1>Malls#show</h1>
<p>Find me in app/views/malls/show.html.erb</p>